// packages/mfe-angular/src/testing/index.ts
/**
 * `@company/mfe-angular/testing` — author testing utilities, never imported by the production
 * entry and never supplying live credentials. The mount helpers place a definition through the
 * runtime's `mountDefinition` — the path every host takes — over a runtime with nothing behind it
 * but memory, so what a test mounts is exactly what a shell would.
 */

import {
  createComponent,
  EnvironmentInjector,
  getDebugNode,
  provideExperimentalZonelessChangeDetection,
  type ApplicationRef,
  type ComponentRef,
  type EnvironmentProviders,
  type Provider,
  type Type,
} from '@angular/core'
import { createApplication } from '@angular/platform-browser'
import {
  createMfeError,
  withoutUndefined,
  type MfeError,
  type UserStorageAdapter,
} from '@company/mfe-core'
import {
  mountDefinition,
  type DefinitionMount,
  type WidgetDefinitionMount,
} from '@company/mfe-runtime'
import {
  createMemoryRuntime,
  type MemoryRuntime,
  type MemoryRuntimeOptions,
  type StoredSeed,
} from '@company/mfe-runtime/testing'

import type { AppDefinition, MfeDefinition, WidgetDefinition } from '../definition.ts'
import { provideMfeRuntime } from '../host/provide-runtime.ts'

/**
 * The runtime's own test surface: the memory runtime, its loader, bridge, storage and telemetry,
 * and the generated-alias fixtures with `resetGeneratedAliases`.
 */
export * from '@company/mfe-runtime/testing'

/** The same storage options as React's `createMfeTestEnvironment`, over the memory runtime's. */
export interface MfeTestEnvironmentOptions extends Omit<MemoryRuntimeOptions, 'storage'> {
  /**
   * Stored values in place before anything mounts, in any area. Each belongs to the key's owner,
   * else the only definition listed, else the host page, unless the seed names its owner.
   */
  readonly storage?: readonly StoredSeed[]
  /** The `user` backend; an in-memory one, seeded from `storage`, when omitted. */
  readonly userStorage?: UserStorageAdapter
  /**
   * The host-supplied placement identity seeded `perInstance` values belong to; `mountWidget`
   * also places the Widget with it.
   */
  readonly instanceId?: string
}

export interface MfeTestEnvironment extends MemoryRuntime {
  /** `provideMfeRuntime(runtime)`, for a host component under test outside any mount. */
  readonly providers: EnvironmentProviders
}

/** Only the options a memory runtime reads, so an absent one stays absent. */
function memoryOptions({
  storage,
  userStorage,
  instanceId,
  ...rest
}: MfeTestEnvironmentOptions): MemoryRuntimeOptions {
  const values = storage?.map(([key, value, caller]): StoredSeed => [
    key,
    value,
    { ...withoutUndefined({ instanceId }), ...caller },
  ])
  return {
    ...rest,
    ...(values === undefined && userStorage === undefined
      ? {}
      : { storage: withoutUndefined({ values, user: userStorage }) }),
  }
}

/** Every environment is independent, so no singleton leaks state between tests. */
export function createMfeTestEnvironment(
  options: MfeTestEnvironmentOptions = {},
): MfeTestEnvironment {
  const memory = createMemoryRuntime(memoryOptions(options))
  return { ...memory, providers: provideMfeRuntime(memory.runtime) }
}

interface PlacementOptions extends MfeTestEnvironmentOptions {
  /**
   * Mounts into an environment the test owns, which the returned `dispose` leaves alive. It has
   * to list the definition among its `definitions`, as a shell's registry lists what it mounts.
   */
  readonly environment?: MfeTestEnvironment
}

export interface MountedTestDefinition {
  /** The scope root the runtime created for the mount, attached to `document.body`. */
  readonly element: HTMLElement
  readonly environment: MfeTestEnvironment
  /** The mount's application injector, where an App's `Router` lives. */
  readonly injector: EnvironmentInjector
  /** Resolves once zoneless change detection has nothing left to do. */
  whenStable(): Promise<void>
  dispose(): Promise<void>
}

export interface MountAppOptions extends PlacementOptions {
  /** The boundary the App is mounted at; the memory history starts there unless told otherwise. */
  readonly basePath?: string
}

export interface WidgetOutput {
  readonly name: string
  readonly payload: unknown
}

export interface MountWidgetOptions extends PlacementOptions {
  readonly inputs?: Readonly<Record<string, unknown>>
  readonly onOutput?: (name: string, payload: unknown) => void
}

export interface MountedTestWidget extends MountedTestDefinition {
  /** Every output the Widget emitted and its contract accepted, in order. */
  readonly outputs: readonly WidgetOutput[]
  /** Every later input set the Widget rejected, in order. */
  readonly rejectedInputs: readonly MfeError[]
  /** Replaces the inputs and waits for the Widget to render them. */
  update(inputs: Readonly<Record<string, unknown>>): Promise<void>
}

/** What a test forgot to dispose, disposed by `cleanup()` so nothing leaks into the next test. */
const live = new Set<() => Promise<void>>()

/**
 * Disposes every mount, host application and host element these helpers created that is still
 * there; the vitest setup calls it.
 */
export async function cleanup(): Promise<void> {
  for (const dispose of [...live]) await dispose()
}

/** Runs `release` once: when the returned function is called, or on `cleanup()` if it never is. */
function untilCleanup(release: () => void | Promise<void>): () => Promise<void> {
  const dispose = async (): Promise<void> => {
    if (!live.delete(dispose)) return
    await release()
  }
  live.add(dispose)
  return dispose
}

/**
 * An Angular application with no mount around it, which is where shell chrome and host components
 * live: zoneless, with the environment's runtime provided, as a shell boots one. `null` provides
 * no runtime. `cleanup()` destroys it.
 */
export async function createHostApplication(
  environment: MfeTestEnvironment | null,
  providers: readonly (Provider | EnvironmentProviders)[] = [],
): Promise<ApplicationRef> {
  const appRef = await createApplication({
    providers: [
      provideExperimentalZonelessChangeDetection(),
      ...(environment === null ? [] : [environment.providers]),
      ...providers,
    ],
  })
  untilCleanup(() => {
    if (!appRef.destroyed) appRef.destroy()
  })
  return appRef
}

export interface RenderedHost<T> {
  readonly ref: ComponentRef<T>
  /** The host component's element, attached to `document.body`. */
  readonly element: HTMLElement
}

/**
 * Renders `component` as a root view of the host application and waits for it to settle; `setup`
 * runs before the first change detection, so it decides what the first render binds. `cleanup()`
 * removes the element.
 */
export async function renderInHost<T>(
  appRef: ApplicationRef,
  component: Type<T>,
  setup: (instance: T) => void = () => undefined,
): Promise<RenderedHost<T>> {
  const element = document.createElement('div')
  document.body.appendChild(element)
  untilCleanup(() => {
    element.remove()
  })

  const ref = createComponent(component, {
    environmentInjector: appRef.injector,
    hostElement: element,
  })
  setup(ref.instance)
  appRef.attachView(ref.hostView)
  await appRef.whenStable()
  return { ref, element }
}

interface Placement {
  readonly environment: MfeTestEnvironment
  /** The element a host renders and hands the runtime, attached to `document.body`. */
  readonly host: HTMLElement
  /** Removes the host element, and the environment when the helper created it. */
  readonly teardown: () => void
}

function place(definition: MfeDefinition, options: PlacementOptions, basePath: string): Placement {
  const ownsEnvironment = options.environment === undefined
  const environment =
    options.environment ??
    createMfeTestEnvironment({
      ...options,
      definitions: [...(options.definitions ?? []), definition],
      initialEntries: options.initialEntries ?? [basePath || '/'],
    })

  if (!environment.runtime.registry.entries.has(definition.id)) {
    throw createMfeError({
      code: 'registry/invalid-entry',
      id: definition.id,
      operation: 'mount into a test environment',
      expected: `"${definition.id}" among the environment's definitions`,
      observed: 'an environment whose registry does not list it',
      repair:
        'List the definition in createMfeTestEnvironment({ definitions }), or leave out `environment`.',
    })
  }

  const host = document.createElement('div')
  document.body.appendChild(host)

  return {
    environment,
    host,
    teardown: () => {
      host.remove()
      if (ownsEnvironment) environment.dispose()
    },
  }
}

/**
 * The mount's application injector, read from the root component the mount created inside the
 * runtime's target element: a component's injector reaches the environment injector its
 * application created it in. Read from the page because a host holds only the runtime's neutral
 * handle, which never exposes what a definition's `mount` resolved to.
 */
function applicationInjectorOf(scopeRoot: HTMLElement): EnvironmentInjector | undefined {
  const componentHost = scopeRoot.firstElementChild?.firstElementChild
  if (componentHost === null || componentHost === undefined) return undefined
  return (
    getDebugNode(componentHost)?.injector.get(EnvironmentInjector, undefined, {
      optional: true,
    }) ?? undefined
  )
}

/**
 * Settles with the mount: its Angular application once it is mounted, its error once it failed. A
 * failed mount is disposed first, so a rejection leaves nothing of it behind.
 */
async function settle(
  mount: DefinitionMount,
  placement: Placement,
): Promise<{ readonly element: HTMLElement; readonly injector: EnvironmentInjector }> {
  const state = await new Promise<ReturnType<DefinitionMount['getState']>>(resolve => {
    const check = (): boolean => {
      const current = mount.getState()
      if (current.status === 'pending') return false
      resolve(current)
      return true
    }
    if (check()) return
    const unsubscribe = mount.subscribe(() => {
      if (check()) unsubscribe()
    })
  })

  const context = mount.context
  const injector = context === null ? undefined : applicationInjectorOf(context.scopeRoot)
  if (state.status === 'mounted' && context !== null && injector !== undefined) {
    return { element: context.scopeRoot, injector }
  }

  // Its failure is the rejection; a cleanup failure has reached the environment's diagnostics.
  await mount.dispose().catch(() => undefined)
  placement.teardown()
  if (state.status === 'error') throw state.error
  throw createMfeError({
    code: 'mount/failure',
    id: mount.id,
    operation: 'mount into a test environment',
    expected: 'a mounted Angular definition',
    observed:
      state.status === 'disposed'
        ? 'a mount disposed before it settled'
        : 'a mount that created no Angular application',
    repair: 'Mount only definitions created with createApp or createWidget from this package.',
  })
}

function track(mount: DefinitionMount, placement: Placement): () => Promise<void> {
  return untilCleanup(async () => {
    await mount.dispose()
    placement.teardown()
  })
}

/** Mounts a real App through the runtime, over a memory history starting at its boundary. */
export async function mountApp(
  definition: AppDefinition,
  options: MountAppOptions = {},
): Promise<MountedTestDefinition> {
  const basePath = options.basePath ?? ''
  const placement = place(definition, options, basePath)
  const mount = mountDefinition({
    runtime: placement.environment.runtime,
    element: placement.host,
    definitionId: definition.id,
    kind: 'app',
    basePath,
  })

  const { element, injector } = await settle(mount, placement)
  const dispose = track(mount, placement)

  await mount.whenStable()
  return {
    element,
    environment: placement.environment,
    injector,
    whenStable: () => mount.whenStable(),
    dispose,
  }
}

/** Mounts a real Widget through the runtime, with the production validation on both sides. */
export async function mountWidget(
  definition: WidgetDefinition,
  options: MountWidgetOptions = {},
): Promise<MountedTestWidget> {
  const placement = place(definition, options, '')
  const outputs: WidgetOutput[] = []
  const rejectedInputs: MfeError[] = []

  const mount: WidgetDefinitionMount = mountDefinition({
    runtime: placement.environment.runtime,
    element: placement.host,
    definitionId: definition.id,
    kind: 'widget',
    ...(options.instanceId === undefined ? {} : { instanceId: options.instanceId }),
    inputs: options.inputs ?? {},
    onOutput: (name, payload) => {
      outputs.push({ name, payload })
      options.onOutput?.(name, payload)
    },
    onInputRejected: error => {
      rejectedInputs.push(error)
    },
  })

  const { element, injector } = await settle(mount, placement)
  const dispose = track(mount, placement)

  await mount.whenStable()
  return {
    element,
    environment: placement.environment,
    injector,
    outputs,
    rejectedInputs,
    whenStable: () => mount.whenStable(),
    update: async inputs => {
      mount.update(inputs)
      await mount.whenStable()
    },
    dispose,
  }
}

// packages/mfe-react/src/testing/index.tsx
/**
 * `@company/mfe-react/testing` — supported author testing utilities, never imported by the
 * production entry and never supplying live credentials.
 *
 * Two ways to put a definition on the page. `renderApp` and `renderWidget` render its tree in the
 * test's own React tree: fast, synchronous and made for Testing Library, and the tree they render
 * is the `MountTree` a production mount renders. `mountApp` and `mountWidget` place it the way a
 * host does, through the runtime's `mountDefinition` and the definition's own `mount`, for a test
 * about loading, retry, disposal or anything else the host decides.
 */

import {
  withoutUndefined,
  type Diagnostic,
  type MfeError,
  type ShellTheme,
  type ShellUser,
  type UserStorageAdapter,
} from '@company/mfe-core'
import {
  createMountContext,
  mountDefinition,
  validateProviderInputs,
  type DefinitionMount,
  type MountableAppDefinition,
  type MountableWidgetDefinition,
} from '@company/mfe-runtime'
import {
  createMemoryRuntime,
  type MemoryRuntime,
  type MemoryRuntimeOptions,
  type MemoryStorageArea,
  type RecordingTelemetryProvider,
  type StoredSeed,
} from '@company/mfe-runtime/testing'
import { act, render, waitFor, type RenderResult } from '@testing-library/react'
import type { ReactNode } from 'react'

import { createRouterContext } from '../app-mount.tsx'
import type { AppDefinition, WidgetDefinition } from '../definition.ts'
import { MfeMountProvider } from '../mount-context.tsx'
import { MountTree } from '../mount-tree.tsx'
import type { MfeRouterContext } from '../router-contract.ts'
import { MfeProvider } from '../runtime-context.tsx'
import { withQueryClient, type MfeMount, type MfeRuntime } from '../runtime.ts'
import { deliverWidgetOutput, widgetInputs } from '../widget-props.ts'

/**
 * The runtime's memory fakes and the generated-alias fixtures, so a test imports its adapter's
 * `/testing` and nothing else.
 */
export * from '@company/mfe-runtime/testing'

export interface TestShellState {
  readonly user?: ShellUser | null
  readonly groups?: readonly string[]
  readonly theme?: ShellTheme
}

export interface MfeTestEnvironmentOptions {
  /** The definition id the simulated mount runs as. */
  readonly definitionId?: string
  readonly definitionVersion?: string
  readonly kind?: 'app' | 'widget'
  readonly basePath?: string
  readonly shellState?: TestShellState
  /** Definitions the in-process loader can resolve, by id, whichever adapter built them. */
  readonly definitions?: MemoryRuntimeOptions['definitions']
  readonly initialEntries?: readonly string[]
  /** The host-supplied placement identity, for `perInstance` keys. */
  readonly instanceId?: string
  /** Stored values in place before anything renders, in any area; they belong to the mount. */
  readonly storage?: readonly StoredSeed[]
  /** The `user` backend; an in-memory one, seeded from `storage`, when omitted. */
  readonly userStorage?: UserStorageAdapter
}

export interface MfeTestEnvironment {
  readonly runtime: MfeRuntime
  readonly mount: MfeMount
  /** Wraps components and hooks in the real framework providers. */
  readonly wrapper: (props: { readonly children: ReactNode }) => ReactNode
  /** Typed context for native route tests, with the same mount-owned client. */
  readonly routerContext: MfeRouterContext
  /** Exercises real snapshot and transition behaviour. */
  setShellState(patch: TestShellState): void
  readonly telemetry: RecordingTelemetryProvider
  readonly diagnostics: readonly Diagnostic[]
  readonly navigation: MemoryRuntime['navigation']
  /** The injected browser stores, which count the calls made against them. */
  readonly storageAreas: {
    readonly local: MemoryStorageArea
    readonly session: MemoryStorageArea
  }
  dispose(): Promise<void>
}

/** Only the options a memory runtime reads, so an absent one stays absent. */
function memoryOptions(options: MfeTestEnvironmentOptions): MemoryRuntimeOptions {
  const owner = options.definitionId ?? 'test-definition'
  const values = options.storage?.map(
    ([key, value, caller]): StoredSeed => [
      key,
      value,
      { owner, ...withoutUndefined({ instanceId: options.instanceId }), ...caller },
    ],
  )
  return withoutUndefined({
    shellState: options.shellState,
    definitions: options.definitions,
    initialEntries: options.initialEntries,
    storage:
      values === undefined && options.userStorage === undefined
        ? undefined
        : withoutUndefined({ values, user: options.userStorage }),
  })
}

/**
 * The runtime's memory runtime plus what is React's: a mount with its Query client, the providers,
 * and the router context. Every environment is independent, so no module state leaks between
 * tests.
 */
export function createMfeTestEnvironment(
  options: MfeTestEnvironmentOptions = {},
): MfeTestEnvironment {
  const memory = createMemoryRuntime(memoryOptions(options))
  const { runtime } = memory

  const handle = createMountContext({
    runtime,
    definitionId: options.definitionId ?? 'test-definition',
    ...withoutUndefined({ definitionVersion: options.definitionVersion }),
    kind: options.kind ?? 'app',
    ...withoutUndefined({ basePath: options.basePath, instanceId: options.instanceId }),
  })
  const mount = withQueryClient(handle.context)

  return {
    runtime,
    mount,
    wrapper: ({ children }) => (
      <MfeProvider runtime={runtime}>
        <MfeMountProvider mount={mount}>{children}</MfeMountProvider>
      </MfeProvider>
    ),
    routerContext: createRouterContext(mount),
    // Wrapped in `act` so updates land inside the test's normal React boundary.
    setShellState: patch => {
      act(() => {
        memory.setShellState(patch)
      })
    },
    telemetry: memory.telemetry,
    diagnostics: memory.diagnostics,
    navigation: memory.navigation,
    storageAreas: memory.storageAreas,
    dispose: async () => {
      await handle.dispose()
      memory.dispose()
    },
  }
}

/**
 * Renders a tree that may suspend, inside an awaited act scope: React warns and leaves the tree
 * stuck on its fallback when a component suspends inside an act scope that was never awaited.
 */
export async function renderSuspending(ui: ReactNode): Promise<RenderResult> {
  let result: RenderResult | undefined

  await act(async () => {
    result = render(<>{ui}</>)
    // Yielding inside the act scope lets a suspended load settle before the caller looks.
    await Promise.resolve()
  })

  if (!result) throw new Error('renderSuspending produced no result')
  return result
}

export type RenderAppOptions = MfeTestEnvironmentOptions

export interface RenderedMfe extends RenderResult {
  readonly environment: MfeTestEnvironment
  dispose(): Promise<void>
}

/**
 * Renders into the mount's own scope root, placed in the document the way the runtime places it
 * for a production mount, so a scoped selector and `useScopeRoot` see what they would see there.
 */
function renderInto(environment: MfeTestEnvironment, ui: ReactNode): RenderedMfe {
  const { scopeRoot } = environment.mount
  document.body.appendChild(scopeRoot)
  const result = render(ui, { container: scopeRoot })

  return {
    ...result,
    environment,
    dispose: async () => {
      result.unmount()
      scopeRoot.remove()
      await environment.dispose()
    },
  }
}

/** Renders a real App through the tree production renders, over a test-owned memory history. */
export function renderApp(definition: AppDefinition, options: RenderAppOptions = {}): RenderedMfe {
  const environment = createMfeTestEnvironment({
    ...options,
    definitionId: definition.id,
    ...withoutUndefined({ definitionVersion: definition.version }),
    kind: 'app',
    basePath: options.basePath ?? '',
    definitions: [...(options.definitions ?? []), definition],
  })

  return renderInto(environment, <MountTree definition={definition} mount={environment.mount} />)
}

export interface RenderWidgetOptions extends MfeTestEnvironmentOptions {
  /** Inputs and `onX` handlers, split exactly as a host splits a consumer's props. */
  readonly props?: Readonly<Record<string, unknown>>
}

/** Renders a real Widget definition with the production validation path. */
export function renderWidget(
  definition: WidgetDefinition,
  options: RenderWidgetOptions = {},
): RenderedMfe {
  const props = options.props ?? {}
  const first = validateProviderInputs(definition, widgetInputs(props))
  if (first.status !== 'accepted') throw first.error
  const environment = createMfeTestEnvironment({
    ...options,
    definitionId: definition.id,
    ...withoutUndefined({ definitionVersion: definition.version }),
    kind: 'widget',
    definitions: [...(options.definitions ?? []), definition],
  })

  return renderInto(
    environment,
    <MountTree
      definition={definition}
      mount={environment.mount}
      inputs={first.value}
      emit={(output, payload) => {
        deliverWidgetOutput(props, output, payload)
      }}
    />,
  )
}

interface PlacementOptions extends MemoryRuntimeOptions {
  /** Mounts into a runtime the test owns, which the returned `dispose` leaves alive. */
  readonly memory?: MemoryRuntime
}

export interface MountedTestDefinition {
  /** The scope root the runtime created for the mount, attached to `document.body`. */
  readonly element: HTMLElement
  readonly memory: MemoryRuntime
  /** The runtime's handle on the mount: its state, `retry` and `context`. */
  readonly mount: DefinitionMount
  /** Disposes the mount, removes the element, and disposes the runtime if it made it. */
  dispose(): Promise<void>
}

export interface MountAppOptions extends PlacementOptions {
  /** The boundary the App is mounted at; the memory history starts there unless told otherwise. */
  readonly basePath?: string
}

export interface WidgetOutput {
  readonly name: string
  readonly payload: unknown
}

export interface MountWidgetOptions extends PlacementOptions {
  readonly inputs?: Readonly<Record<string, unknown>>
  readonly onOutput?: (name: string, payload: unknown) => void
}

export interface MountedTestWidget extends MountedTestDefinition {
  /** Every output the Widget emitted and its contract accepted, in order. */
  readonly outputs: readonly WidgetOutput[]
  /** Every later input set the Widget rejected, in order. */
  readonly rejectedInputs: readonly MfeError[]
  /** Replaces the inputs, as a host re-rendering with new props does. */
  update(inputs: Readonly<Record<string, unknown>>): void
}

interface Placement {
  /** The element a host renders and hands the runtime, attached to `document.body`. */
  readonly host: HTMLElement
  readonly memory: MemoryRuntime
  /** Disposes the mount, removes the host element, and the runtime when this made it. */
  readonly teardown: (mount: DefinitionMount) => Promise<void>
}

function place(
  definition: MountableAppDefinition | MountableWidgetDefinition,
  { memory: provided, ...runtimeOptions }: PlacementOptions,
  basePath: string,
): Placement {
  const memory =
    provided ??
    createMemoryRuntime({
      ...runtimeOptions,
      definitions: [...(runtimeOptions.definitions ?? []), definition],
      initialEntries: runtimeOptions.initialEntries ?? [basePath || '/'],
    })

  const host = document.createElement('div')
  document.body.appendChild(host)

  return {
    host,
    memory,
    teardown: async mount => {
      await mount.dispose()
      host.remove()
      if (provided === undefined) memory.dispose()
    },
  }
}

/**
 * Resolves once the mount settled: with the mounted definition, or by rejecting with the error the
 * mount failed with, after disposing everything it made. Waits through Testing Library, which
 * lets a React root render on React's own scheduler while it polls.
 */
async function settled(mount: DefinitionMount, placement: Placement): Promise<HTMLElement> {
  await waitFor(() => {
    if (mount.state.status === 'pending') throw new Error(`${mount.id} is still mounting`)
  })

  const { state, context } = mount
  if (state.status === 'error') {
    await placement.teardown(mount)
    throw state.error
  }
  if (context === null) throw new Error(`${mount.id} settled without a mount context`)
  return context.scopeRoot
}

/** Mounts a real App the way every host does, over a memory history starting at its boundary. */
export async function mountApp(
  definition: MountableAppDefinition,
  options: MountAppOptions = {},
): Promise<MountedTestDefinition> {
  const { basePath = '', ...placementOptions } = options
  const placement = place(definition, placementOptions, basePath)
  const mount = mountDefinition({
    runtime: placement.memory.runtime,
    element: placement.host,
    definitionId: definition.id,
    kind: 'app',
    basePath,
  })

  const element = await settled(mount, placement)
  return {
    element,
    memory: placement.memory,
    mount,
    dispose: () => placement.teardown(mount),
  }
}

/** Mounts a real Widget the way every host does, with the production validation on both sides. */
export async function mountWidget(
  definition: MountableWidgetDefinition,
  options: MountWidgetOptions = {},
): Promise<MountedTestWidget> {
  const { inputs = {}, onOutput, ...placementOptions } = options
  const placement = place(definition, placementOptions, '')
  const outputs: WidgetOutput[] = []
  const rejectedInputs: MfeError[] = []

  const mount = mountDefinition({
    runtime: placement.memory.runtime,
    element: placement.host,
    definitionId: definition.id,
    kind: 'widget',
    inputs,
    onOutput: (name, payload) => {
      outputs.push({ name, payload })
      onOutput?.(name, payload)
    },
    onInputRejected: error => {
      rejectedInputs.push(error)
    },
  })

  const element = await settled(mount, placement)
  return {
    element,
    memory: placement.memory,
    mount,
    outputs,
    rejectedInputs,
    update: next => {
      mount.update(next)
    },
    dispose: () => placement.teardown(mount),
  }
}
