// packages/mfe-angular/src/inject/shared-state.ts
import { assertInInjectionContext, type Signal } from '@angular/core'
import {
  SharedStateError,
  type SharedStateSetter,
  type SharedStateStore,
  type StateKey,
} from '@company/mfe-core/shared-state'
import { signalFromStore } from '../signals.ts'
import { injectMfeMount } from './runtime.ts'

export type { SharedStateStore, SharedStateSetter } from '@company/mfe-core/shared-state'

/** Per-injector bindings work in components, services, route guards and resolvers. */
export function createSharedStateBindings<V>(definitionId: string) {
  function injectSharedStateStore(): SharedStateStore<V> {
    assertInInjectionContext(injectSharedStateStore)
    const mount = injectMfeMount('injectSharedStateStore()')
    if (mount.definitionId !== definitionId || !mount.sharedState)
      throw new SharedStateError(
        'unsupported-contract',
        definitionId,
        'Use the generated binding for this mounted definition',
      )
    return mount.sharedState as SharedStateStore<V>
  }
  function injectSharedState<K extends StateKey<V>>(
    key: K,
  ): readonly [Signal<V[K]>, SharedStateSetter<V[K]>] {
    assertInInjectionContext(injectSharedState)
    const store = injectSharedStateStore()
    return [
      signalFromStore(
        listener => store.subscribe(key, listener),
        () => store.get(key),
      ),
      value => store.set(key, value),
    ]
  }
  return { injectSharedState, injectSharedStateStore }
}

// packages/mfe-react/src/hooks/shared-state.ts
import { useCallback, useSyncExternalStore } from 'react'
import {
  SharedStateError,
  type SharedStateSetter,
  type SharedStateStore,
  type StateKey,
} from '@company/mfe-core/shared-state'
import { useMfeMount } from '../mount-context.tsx'

/** Generated once per definition; only closures over immutable metadata, never a store singleton. */
export function createSharedStateBindings<V>(definitionId: string) {
  function useSharedStateStore(): SharedStateStore<V> {
    const mount = useMfeMount('useSharedStateStore()')
    if (mount.definitionId !== definitionId || !mount.sharedState)
      throw new SharedStateError(
        'unsupported-contract',
        definitionId,
        'Use the generated binding for this mounted definition',
      )
    return mount.sharedState as SharedStateStore<V>
  }
  function useSharedState<K extends StateKey<V>>(key: K): readonly [V[K], SharedStateSetter<V[K]>] {
    const store = useSharedStateStore()
    const subscribe = useCallback(
      (listener: () => void) => store.subscribe(key, listener),
      [store, key],
    )
    const getSnapshot = useCallback(() => store.get(key), [store, key])
    const set = useCallback((value: V[K]) => store.set(key, value), [store, key])
    return [useSyncExternalStore(subscribe, getSnapshot), set]
  }
  return { useSharedState, useSharedStateStore }
}
